title: Java Best Practices
email: jonathan@jonathangiles.net
url: "https://java.jonathangiles.net"

defaults:
  - 
    scope:
      path: ""
    values:
      author:
        name: Jonathan Giles
        email: jonathan@jonathangiles.net